# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opera',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='opera',
            name='writing_date',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
