# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160803_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('file_digest', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
