# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='attach',
            name='opera_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
