# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_attach_opera_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attach',
            name='file_upload',
            field=models.FileField(default=0, upload_to=b''),
            preserve_default=False,
        ),
    ]
