# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_attach_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attach',
            name='file_digest',
        ),
        migrations.RemoveField(
            model_name='attach',
            name='opera_id',
        ),
        migrations.RemoveField(
            model_name='opera',
            name='media_data',
        ),
        migrations.AddField(
            model_name='opera',
            name='media',
            field=models.ManyToManyField(to='webapp.Attach'),
        ),
        migrations.AlterField(
            model_name='attach',
            name='file_upload',
            field=models.FileField(upload_to='documents'),
        ),
    ]
